package dir.tests;// Generated by Selenium IDE
import dir.model.AccountData;
import org.junit.Test;
import org.junit.Assert;

import java.util.concurrent.TimeUnit;

public class AuthorizationTest extends TestBase {
    @Test
    public void login() {
        app.getNavigation().GoToHomePage();
        try {
            TimeUnit.SECONDS.sleep(1);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        AccountData user = new AccountData("gismagilova402@gmail.com", "gusenica");
        app.getAuth().Login(user);

        Assert.assertTrue("Пользователь не залогинен", app.getAuth().isLoggedIn());
    }
}

