package dir.tests;// Generated by Selenium IDE
import dir.model.AccountData;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;

import javax.swing.plaf.PanelUI;

public class AuthorizationTest extends TestBase {
    @Test
    public void account() {
        login();
        logout();
    }

    public void login() {
        app.getNavigation().GoToHomePage();
        AccountData user = new AccountData("gismagilova402@gmail.com", "gusenica");
        app.getAuth().Login(user);
    }

    public void logout() {
        app.getAuth().Logout();
    }
}

