package dir.tests;// Generated by Selenium IDE
import org.junit.Assert;
import org.junit.Test;

import java.util.concurrent.TimeUnit;

public class LogoutTest extends AuthBase {
    @Test
    public void logout() {
        try {
            TimeUnit.SECONDS.sleep(1);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        app.getAuth().Logout();

        Assert.assertTrue("Пользователю не удалось выйти", app.getAuth().isLoggedOut());
    }
}

