package dir.tests;// Generated by Selenium IDE
import dir.model.NoteData;
import org.junit.Assert;
import org.junit.Test;

import java.util.concurrent.TimeUnit;

public class NoteCreationTest extends TestBase {
    @Test
    public void createNote() {
        int before = app.getNote().getNotesCount();

        try {
            TimeUnit.SECONDS.sleep(3);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        NoteData note = new NoteData("");
        app.getNote().AddNewNote(note);

        int after = app.getNote().getNotesCount();

        Assert.assertEquals("Заметка не была создана", before + 1, after);
    }
}



