package dir.tests;// Generated by Selenium IDE
import dir.model.AccountData;
import dir.model.NoteData;
import dir.tests.TestBase;
import org.checkerframework.checker.units.qual.A;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;

import java.util.concurrent.TimeUnit;

public class NoteCreationTest extends TestBase {
    @Test
    public void createNote() {
        try {
            TimeUnit.SECONDS.sleep(3);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        NoteData note = new NoteData("");
        app.getNote().AddNewNote(note);
    }
}



