package dir.tests;// Generated by Selenium IDE
import dir.TestDataFileReader;
import dir.model.NoteData;
import org.junit.Assert;
import org.junit.Test;

import java.io.IOException;
import java.util.List;
import java.util.concurrent.TimeUnit;
import org.junit.runner.RunWith;
import org.junit.runners.Parameterized;

@RunWith(Parameterized.class)
public class NoteCreationTest extends TestBase {

    private NoteData noteData;

    // Конструктор, который принимает NoteData
    public NoteCreationTest(NoteData noteData) {
        this.noteData = noteData;
    }
    @Parameterized.Parameters
    public static List<NoteData> testData() throws IOException {
        return TestDataFileReader.readTestData("C:\\Users\\gisma\\IdeaProjects\\Tests\\data.xml");
    }

    @Test
    public void createNote() {
        int before = app.getNote().getNotesCount();

        try {
            TimeUnit.SECONDS.sleep(3);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }

        app.getNote().AddNewNote(noteData);

        int after = app.getNote().getNotesCount();

        Assert.assertEquals("Заметка не была создана", before + 1, after);
    }
}



